### ISSUE TITLE
Add `aah migrate` command to fix/upgrade application codebase to latest aah version

### ISSUE THREAD

**Issue by jeevatkm** [go-aah/aah#116]
The goal is to bring `aah migrate` command to easy the upgrade or fix the aah framework breaking changes and deprecated elements in `.go` files and basic template file support.

**Limitation:**
To begin with `migrate` command does not support config files; it should be done manually, later I will add it.

- [x] Implementation
- [x] Documentation

**Comment by julienkosinski** [comment]
@jeevatkm About config file, when you'll add it update template directly with new config and comments (because config file are always really well commented) with an auto-merging process (like git could do with pulling commits).

For resolving conflicts some of them could modify the project with find/replace. I'm thinking of something like obvious typo change in API...
For all the complexe changes to make I'm thinking of logging in CLI each modifications and actions required and modify the file in which an action is required adding comments in the problematic line to help resolve the problem (maybe the same comments logged in CLI)

**Comment by jeevatkm** [comment]
@julienkosinski That's good suggestion. I agree, logging information via CLI would be helpful.

**Comment by julienkosinski** [comment]
@jeevatkm Also, as config files updates regularly with new versions to update documentations, efforts should be made about this.

I know that (learn just now in fact), for example, modern javascript front-end scaffolding apps handle this by avoiding default config and providing config repo kept up-to-date with best-practices for each use cases. (See [POI](https://poi.js.org), [here](https://github.com/egoist/poi/tree/master/packages) for example).

I suppose in our case the best way is to design the upgrade tool so that it merges config file but having a repo for config is not stupid because there's multiple config use cases to handle (and the created app needs to keep the info of what type of app it is and updates it accordingly, is it web or api, form or basic,  etc).

What's your thought about this :)?

**Comment by jeevatkm** [comment]
@julienkosinski I have read and went through your references of config templates idea. Looks interesting.

I will have to do analysis and homework on config template to see; it is feasible to accommodate in aah and Go. Will get back to you.

I would like to do proper homework before touching migrate command implementation.

**Comment by jeevatkm** [comment]
Implementation is done (I would call it beta to begin with; gradually it will get more mature). 

Have to work in documentation 😄

**Comment by jeevatkm** [comment]
Its finally done, thank you for patience.
