### ISSUE TITLE
Route translation

### ISSUE THREAD

**Issue by tobyjwebb** [go-aah/aah#131]
Would it be possible to implement a route translator?

Something like this PHP Symfony bundle: http://jmsyst.com/bundles/JMSI18nRoutingBundle/master/usage

So having different routes like:
/en/home
/es/inicio
would point to the same controller, having all the routes in a translation configuration file.

**Comment by jeevatkm** [comment]
@tobyjwebb Internationalization via path param is out-of-the-box feature in aah.

Refer to this tutorial https://docs.aahframework.org/tutorial/i18n-url-path-param.html

Basically, how it works:
* Messages defined in i18n config files for every locale you would like do have Internationalization
* Those message keys is used in the view files 
* Path locale key `:lang` is defined in `routes.conf` for the path needs to be translated 
* When request `/en/home` (route: /:lang/home) coming in, aah automatically take cares of Internationalization. Also you can map multiple routes into one controller and its action

Please let me know your follow up questions.

**Comment by jeevatkm** [comment]
@tobyjwebb Does it satisfy your use case?

**Comment by tobyjwebb** [comment]
Hi

It's not quite as clean as the symfony solution, but yes, I think it will
do. Thanks!

Regards,

Toby

**Comment by jeevatkm** [comment]
@tobyjwebb I'm actually glad to hear your open feedback. It would really help to improve aah.  I need your inputs, so that I can improve `aah` in upcoming releases.

I'm gonna try to map the documentation reference you have provided (http://jmsyst.com/bundles/JMSI18nRoutingBundle/master/usage) into aah:

**Default behavior of aah is:**
Every view i18n keys are translated based on Request Context i.e HTTP header `Accept-Language`.

For example: Let's say you have route named `home` in the routes.conf; this gets translated automatically into all defined locales in `<app-base-dir>/i18n/*` directory.
```
home {
   path = "/home"
   controller = "HomeController"
   action = "Index"
}
```
It means, when user visits the page `http://example.com/home` aah automatically presents the view based on user locale when visiting your web application.

**Generating Route/Page translation:** Upcoming feature
I will be bringing `aah generate` cmd for generating i18n locale file from view file #119 

**Localized route definition:**
Defining route for the localization. Having locale name on the URL path.
```
home {
   path = "/:lang/home"
   controller = "HomeController"
   action = "Index"
}
```
So this maps to `/en/home`, `/es/home`, etc.

**Reverse URL generation:**
This is two template functions [rurl](https://docs.aahframework.org/template-funcs.html#func-rurl) and [rurlm](https://docs.aahframework.org/template-funcs.html#func-rurlm) for route generation on the view.

```
<!-- uses locale of the request context to PRESENT the home route -->
<a href="{{ rurl . "home" }}">Home</a>

<!-- IF YOU HAVE DEFINED route with locale name, then you can do; passing locale explicitly.
Then view is presented based on the locale from the URL -->
<a href="{{ rurl . "home" "de" }}">Deutsch</a>
<a href="{{ rurl . "home" "en" }}">English</a>
```

**Leaving routes untranslated** 
Currently if locale is not defined in `<app-base-dir>/i18n/*` directory. Then `aah` fallbacks to default locale based on config `i18n.default` from `aah.conf`

I think, I will this information into documentation too. It would be helpful.

**Comment by jeevatkm** [comment]
Also you can override the request context locale value via URL query parameter.

For example: Let's say your `i18n.default = "es"`, you can do the following out-of-the-box

* `http://example.com/home` displays `es` locale
* `http://example.com/home?lang=en` displays `en` locale
* `http://example.com/home?lang=de` displays `de` locale
* etc.

You can customize the param name `lang` via `i18n.param_name.query = "locale"`

**Comment by jeevatkm** [comment]
I'm closing it. Please feel free share your inputs for the improvements.
