### ISSUE TITLE
Docs issue in "Getting started".

### ISSUE THREAD

**Issue by frederikhors** [go-aah/aah#252]
Docs issue in "Getting started":

![image](https://user-images.githubusercontent.com/41120635/54240859-981f4680-451f-11e9-846b-db80080c7d70.png)

**Comment by jeevatkm** [comment]
@frederikhors Thank you for reporting it. I will update the document. It seems like `asciinema.org` user account issue.

**Comment by jeevatkm** [comment]
@frederikhors I have addressed the Docs issue, could you please check it?

**Comment by frederikhors** [comment]
@jeevatkm amazing!

You product is awesome! Really! What scares me and stops me for a go-live system with aah for large projects is the low diffusion (at least apparent) and the few contributors (ie only you practically).

**Comment by jeevatkm** [comment]
@frederikhors I understand what you mean. aah's first public release happened in May 2017, since then it gradually growing, features are getting added and maturing. So far many users are using also I'm getting valuable feedback, feature requests, etc and aah has good coverage of documentation and examples.

I strongly believe aah will gain its name and users over a period of time. Maybe you could try out aah for a small project to start with to gain confidence then you could take the decision for large projects.

One of the key feature of aah, its simple structure, and APIs so its easy grasp what's going on.

I'm looking forward to your valuable feedback and contributions 😄 

----

I'm closing this doc issue.
