### ISSUE TITLE
add a cache repository

### ISSUE THREAD

**Issue by ghost** [go-aah/aah#56]
link: https://github.com/go-aah/cache or https://github.com/aah-cb/redis-cache

I am responsible for the completion

**Comment by elevenbag** [comment]
@jeevatkm

**Comment by jeevatkm** [comment]
I appreciate your interest and contribution. I have created a [redis-cache](https://github.com/aah-cb/redis-cache) repository and added you.

I have not yet created aah framework code quality guidelines. Planning to publish as part of v0.6 release.

It is typical and easy. 

* Please go throuh the aah codebase how it is organized in the go source file.
* Go [conventions](https://golang.org/doc/effective_go.html) and godoc
* I use `gometaliner` with this config
```
--vendor, --disable-all, --enable=vet, --enable=vetshadow, --enable=golint, --enable=ineffassign, --enable=goconst, --enable=errcheck, --enable=dupl, --enable=interfacer, --enable=unconvert, --enable=gosimple, --enable=misspell, --enable=unused, --enable=deadcode, --enable=gotype, --enable=gocyclo, --cyclo-over=15, --tests, --json, .
```
* Please have a look at this [README.md](https://github.com/go-aah/aah/blob/v0-unstable/README.md) for badges needs to be done before the release.
* When you're ready for the release, please let me know. I will discuss with you
* I will be enabling travis ci for this repo, once done I will let you know.

BTW, I have a question. After the first release would you like be lead maintainer and own `redis-cache` library? If answer yes, please let me know.

**Comment by elevenbag** [comment]
@jeevatkm    yes,I will maintain my own redis-cache library

**Comment by jeevatkm** [comment]
Thank you @elevenbag. Glad to know your response. I will add the repo details and your name into [team page](https://aahframework.org/team.html) after the first release.

I have enabled the Travis CI integration for `redis-cache`. You can add `.travis.yml` and build it. Please refer this [.travis.yml](https://github.com/go-aah/aah/blob/v0-unstable/.travis.yml)

I have enabled the [code cov integration](https://codecov.io/gh/aah-cb/redis-cache) for code coverage. You will this configuration in .travis.yml file.

**Comment by jeevatkm** [comment]
@elevenbag Please refer development and release process here 

https://docs.aahframework.org/release-and-development-process.html

**Comment by adelowo** [comment]
@elevenbag and @jeevatkm, I maintain onecache (https://github.com/adelowo/onecache) already. It comes with adapters for Redis, Memcached, Filesystem and an inmemory store.. If it seems like a viable option, I would be interested in assisting to make it easier to use for aah projects

**Comment by jeevatkm** [comment]
@adelowo Thanks for your inputs. Now I'm occupied with v0.6 release.  I will go thru onecache library and get back to you with my thoughts later on.

@elevenbag I would like to hear your thoughts too.

**Comment by jeevatkm** [comment]
@adelowo Thank you for your patience, after v0.6 release I took a time to go through onecache library. I would like to mention you have done a good work on onecache library and it is currently at `v2.2.1`. You and I have same idea.

Honestly I didn't plan to add the cache support for a while, that's why it's not on roadmap right now. Gradually I planned to add it.

**Following is my thoughts on it:**

We both have same idea, however my design thoughts and implementation approach differs.
* Have common interface as same as yours and providing methods for basic data type support int, int64, string, float32, float64, and bool.
* Also Expose underlying cache client, since common interface doesn't provide cache backend capabilities. For e.g. Redis so it is must expose it.
* Only In-memory cache is included in the framework out-of-the-box then providing pluggable option for other cache backends via `github/aah-cb/*`.  So that aah user can use only needed library instead every backend cache options.
* As a framework it is must have an abstraction with third party libraries and also have to provide composable option for the user.
* I would to love follow Go conventions, if you go through the framework codebase you will see what I mean. As of now I have not published the coding guidelines but I have followed so many into implementation to provide quality and performant codebase.

It seems @elevenbag user is not exists in Github anymore. I have just deleted the repo `aah-cb/redis-cache`.

If you interested after going through above thoughts and ready to help and work on development. I'm willing to create a repo which will be referred as `aahframework.org/cache.v0`. So that we can implement above thoughts and pluggable cache backends one by one via `github.com/aah-cb/*` gradually.

Look forward to hear your answer. I will surely work with you so not to worry.

**Comment by adelowo** [comment]
Sure, I would like to help out with this

**Comment by jeevatkm** [comment]
@adelowo If you would like to work on cache module, please let me know. Otherwise I will close this one and later I will pick it up when I work on per roadmap.

**Comment by jeevatkm** [comment]
Closing this, I will pick it up later per roadmap.
