### ISSUE TITLE
Any benchmark ?

### ISSUE THREAD

**Issue by rebootcode** [go-aah/aah#81]
Go is already powerful , but still many people like me are bechmarkoholic . Does aah has any benchmark graph against other go web framework ?

**Comment by jeevatkm** [comment]
@rebootcode Thank you for your interest and considering aah framework.

As of now I have not yet created benchmark suite against other go web framework. However I did benchmark of aah (which is not in presentable state) and then submitted aah framework v0.6 release on [TechEmpower Framework Benchmark](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Go/aah). It will be added in the next round.

I'm currently occupied with upcoming release `v0.7` of major milestones #37, #4 and [more](https://github.com/go-aah/aah/milestone/7). 

For now, I would request and suggest; please go through [aah features](https://aahframework.org/features.html) and do your benchmark as per your use case. I believe it would give satisfying results for you. If you come across any bottleneck, kindly report it.

I will keep this issue open, so that I can track and bring benchmark gradually. Thanks.

**Comment by rebootcode** [comment]
Great! Also another small question :- 

1. Does aah has "file based session" and not memory based session . ( Memory based session without proper GC for expired cookies has lots of issues with memory leak )
=> Never mind , found this on feature list . `Out-of-the-box cookie and file session store is supported.`

2. Does it has `secure cookie` option ?

3. Does it uses "fasthttp" or default "net/http" 

I will definitely look into code and contribute.

Cheers.

**Comment by jeevatkm** [comment]
@rebootcode My response as follows:

> Does aah has "file based session" and not memory based session . ( Memory based session without proper GC for expired cookies has lots of issues with memory leak )

As you found on the feature list, Yes aah supports cookie and file based session store. Also you can register your choice session store implementation, refer [here](https://docs.aahframework.org/session.html) and aah has expired session cleanup support based on [config](https://docs.aahframework.org/security-config.html#cleanup-interval) for file based session store. 

> Does it has secure cookie option ?

Yes, refer to [security - session config](https://docs.aahframework.org/v0.6/security-config.html)

> Does it uses "fasthttp" or default "net/http"

aah uses default `net/http` HTTP/1.1 and HTTP/2 supported.

Glad to hear, will look forward to your contribution.

Thanks.

**Comment by jeevatkm** [comment]
@rebootcode I hope your assessment is progressing well. Let me know if you have any queries or need assistance.

**Comment by rebootcode** [comment]
@jeevatkm , currently i am building up App using one of golang-iris framework fork. I am not convinced with that golang-iris framework fork, but for me performance and security is always priority, so once i am done with my app which has already crossed half of work, i will dig in to Aah Framework and will participate more here. This  framework definitely looks promising.

Cheers

**Comment by jeevatkm** [comment]
@rebootcode Sounds good. Thanks.

**Comment by jeevatkm** [comment]
@rebootcode I thought to ping you regarding security. `aah` provides flexible and powerful security module.

You mentioned your priority of security and performance. I'm sure it would you satisfy your application requirements. Please have a look on documentation. Thanks.

**Comment by rebootcode** [comment]
Hi @jeevatkm - I really enjoyed creating small QnA app with aah-framework. It was with previous release. Aah-Framework needs little tweak - will send some PR, when I have left iris. 
As for now, Temporarily, I have stick back with iris, as it has returned back with some goodness and is definitely showing great benchmark.

**Comment by jeevatkm** [comment]
@rebootcode Thank you for your feedback. I'm glad to hear you have enjoyed with aah framework.

Feel free to send the PR 😄
